# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c53e6a6a7cbef87fe8af45ba3b342786"
application_url = "https://watermark-app-kudh.vercel.app"
embedded = true
name = "testing-app"
handle = "testing-app-918"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://watermark-app-kudh.vercel.app/auth/callback",
  "https://watermark-app-kudh.vercel.app/auth/shopify/callback",
  "https://watermark-app-kudh.vercel.app/api/auth/callback"
]

[pos]
embedded = false

[[ui.extensions]]
type = "theme_app_extension"
name = "Product Button Embed"
target = "theme"
